name: Build and Test

on: [push, pull_request]

defaults:
  run:
    shell: bash

env:
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:

  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]
        python-version: [3.8]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: s-weigand/setup-conda@v1
      if: matrix.os == 'windows-latest'
      with:
        update-conda: true
        conda-channels: conda-forge
        activate-conda: true
        python-version: ${{matrix.python-version}}
    - name: Install dependencies and yt
      shell: bash
      env:
        dependencies: ${{ matrix.dependencies }}
      run: source ./tests/ci_install.sh
    - name: Run Tests
      run: pytest --html=report.html --self-contained-html
    - uses: actions/upload-artifact@v2
      name: Upload pytest report
      with:
        name: pytest-report
        path: report.html
