name: Check Build

on: [push, pull_request]

jobs:
  build-and-publish:
    name: Build (and Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install pypa/build
      run: python -m pip install build --user
    - name: Build source tarball
      run: python -m build --sdist --outdir dist/ .
